### ISSUE TITLE
[0002] Padronização de commits utilizando commitlint (Padronização de commits/ambiente #46)

### ISSUE THREAD

**Issue by LuizHAP** [diego3g/rsxp-2023#50]
Working #46

**Comment by hnqg** [comment]
@LuizHAP poderia excluir essa issue e comentar que está em WIP na https://github.com/diego3g/rsxp-2023/issues/46?

Dessa forma a gente não deixa ela duplicada

**Comment by diego3g** [comment]
Issue duplicada, já editei o nome da outra issue pra sabermos que está em WIP.
