### ISSUE TITLE
[0001] Configuração de workflows de CI para linting e type checking

### ISSUE THREAD

**Issue by hnqg** [diego3g/rsxp-2023#52]
## Descrição 📝 

Como discutido em https://github.com/diego3g/rsxp-2023/discussions/26, seria importante uma padronização no código que será mergeado na main.

## Objetivo 🎯 

- [x] Implementar scripts para formatação do código 
  - [x] Linter e type checking
- Implementar job de CI que rode estes scripts e o build para garantir que o código não quebra nada da aplicação

## Comportamento esperado 👁️ 

Ao fazer um PR e mergear na master, esse job deve rodar passar com 100% de checks.

**Comment by hnqg** [comment]
WIP

**Comment by EliasGcf** [comment]
Vi agora que já temos essa issue aqui, mas acabei criando a https://github.com/diego3g/rsxp-2023/issues/66.

Vou deixar abaixo o que comentei por lá: 

> Faaala, galera!
> 
> Vou criar os arquivos de workflows para a execução do CI e proponho duas soluções:
> 
> * Ter somente um arquivo `ci.yml` para executar as validações nas PRs, independente de qual projeto foi alterado. (`mobile`, `server`)
> * Ter dois arquivos: `ci-mobile.yml` e `ci-server.yml`, pois assim é possível executar as validações de acordo a qual projeto sofreu alteração. Documentação referente ao filtro de paths: [Workflow syntax for GitHub Actions - GitHub Docs#example-including-paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths)
> 
> O que acham?

@hnqg Você já está trabalhando nisso?

**Comment by hnqg** [comment]
> Vi agora que já temos essa issue aqui, mas acabei criando a #66.
> 
> Vou deixar abaixo o que comentei por lá:
> 
> > Faaala, galera!
> > Vou criar os arquivos de workflows para a execução do CI e proponho duas soluções:
> > 
> > * Ter somente um arquivo `ci.yml` para executar as validações nas PRs, independente de qual projeto foi alterado. (`mobile`, `server`)
> > * Ter dois arquivos: `ci-mobile.yml` e `ci-server.yml`, pois assim é possível executar as validações de acordo a qual projeto sofreu alteração. Documentação referente ao filtro de paths: [Workflow syntax for GitHub Actions - GitHub Docs#example-including-paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths)
> > 
> > O que acham?
> 
> @hnqg Você já está trabalhando nisso?

Opa @EliasGcf, tô sim mano. Devo subir a PR agora de noite.

Eu tava pensando em rodar as validações tanto na app mobile quanto server, garantia nunca é demais hahah

**Comment by EliasGcf** [comment]
Opa @hnqg , entendi.

Imaginando um caso de uma PR que altere somente código no projeto `mobile`, por exemplo, não vejo necessidade de executar essas mesmas validações no projeto `server`. Minha opinião apenas.

@diego3g , o que acha?

**Comment by diego3g** [comment]
@EliasGcf @hnqg acho que podemos executar somente se houver alterações mesmo :)
