### ISSUE TITLE
[0012] Configuração do React Query

### ISSUE THREAD

**Issue by nitoba** [diego3g/rsxp-2023#55]
Olá galera, irei fazer a configuração do React Query no projeto mobile

**Comment by nitoba** [comment]
- Sugestão de organização das requisições em serviços para separar as responsabilidades

## src/services
```ts
export async function getUser() {
  const result = await fetch('https://api.github.com/users/diego3g')
  return await result.json()
}
```

- Sugestão de organização das keys usadas no React Query usando enums
```ts
export enum QueryKeys {
  users = 'users',
}```

**Comment by pedro-lucaas** [comment]
Dessa forma não temos tipagem no retorno das nossas queries. Acho que já podíamos pensar nisso e montar uma estrutura que aceite isso

**Comment by pedro-lucaas** [comment]
Eu gosto de utilizar o axios. O que acham?
Poderíamos na pasta services criar uma pasta api onde ficariam as configurações comuns a todas as requisições, como base url, algum token caso seja necessásrio e etc.
E dentro da pasta api criarmos subpastas com as requisições.

**Comment by pedro-lucaas** [comment]
@hnqg gosto dessa abordagem também. é uma boa!

**Comment by nitoba** [comment]
@pedro-lucaas teriamos sim o retorno da tipagem da forma que vc colocou, mas por enquanto não sabemos se vamos utilizar o axios ou a fetch api. Ao meu ver poderiamos seguir usando o axios pq já tem a questão da tipagem assim como vc colocou passando através dos generics

**Comment by nitoba** [comment]
posso fazer a implementação do Axios junto do projeto se for do acordo de todos, o que acham @pedro-lucaas e @hnqg  ?

**Comment by hnqg** [comment]
Acho legal @nitoba, manda bala!
