### ISSUE TITLE
[0011] Layout da página de "Minha credencial"

### ISSUE THREAD

**Issue by LuisCarlosDev** [diego3g/rsxp-2023#58]
Atualizando hehe, Irei fazer toda a parte visual dessa task, logo depois que @RennanD terminar a #67 eu pego o que ele fez e adiciono na tela!

**Comment by matheralvs** [comment]
Opa @LuisCarlosDev, como não foi passada descrição para essa task, você ficará com a construção da página de minha credencial por completa? Em conversa com o @RennanD, ele disse que está trabalhando para entregar as rotas com esses cabeçalhos padrões da issue #67. O ideal seria que essa task fosse feita em paralelo com a #67. Mas caso tenha outra sugestão, só falar.

**Comment by LuisCarlosDev** [comment]
Opa mano, desculpa a demora! Sim mano irei fazer o layout por completo, Sobre a task #67 eu ainda não tinha visto haha, e ai estava começando a fazer! Mais como já vai ser feito dinâmico  vai bem melhor, ai no caso vou tocando o conteúdo principal da tela!

**Comment by LucasBerce71** [comment]
Alguém finalizou essa task? Se não, eu gostaria de finalizar.

**Comment by LuisCarlosDev** [comment]
Estou fazendo ainda mano!

**Comment by matheralvs** [comment]
> Estou fazendo ainda mano!

Opa @LuisCarlosDev, tá on no discord? Queria dar uma olhada no q tu já fez! Se sim, me dá um toque!

**Comment by MathRMM** [comment]
Gente vcs estão com grupo no disc? estou querendo participar mas ainda estou um pouco perdido

**Comment by diego3g** [comment]
Galera, vão conseguir finalizar essa aqui ou posso fazer?

**Comment by LuisCarlosDev** [comment]
Opa Diegão, desculpa a demora em responder. Então cara estou finalizando o layout, estou com um erro aqui que o ticket não está deixando eu scrollar a tela, estou vendo o que é isso! Mais se quiser que eu atualize o repo posso mandar!

**Comment by diego3g** [comment]
@LuisCarlosDev pode subir numa PR e eu tento ajudar por aqui :)

**Comment by LuisCarlosDev** [comment]
Beleza @diego3g!
