### ISSUE TITLE
Qual lib vai lidar com o roteamento da aplicação mobile?

### ISSUE THREAD

**Issue by pabloykaro** [diego3g/rsxp-2023#6]
Boa noite comunidade, qual vai ser a lib que irá lidar com o roteamento da aplicação ?, tenho algumas sugestões.

1 => Expo Router
2 => React Navigation

**Comment by renaldodev** [comment]
Pergunta pertinente, podia mover essa tua issue para a sessão de discussions, ai assim todo mundo daria a sua opinião .
