### ISSUE TITLE
[0010] Layout do menu de navegação

### ISSUE THREAD

**Issue by LuizHAP** [diego3g/rsxp-2023#64]
Fala galera, blz? Estou trabalhando nessa task juntamente com o @RennanD

**Comment by RennanD** [comment]
@LuizHAP Essa issue seria para criar esse componente?

![Captura de Tela 2023-04-05 às 16 05 41](https://user-images.githubusercontent.com/15038553/230180188-417b9082-708a-498d-a15b-c0201f5044c4.png)

Se sim, tens alguma ideia para criar ele? Quando criei a configuração de rotas optei por não criar criar um `Drawer Navigation` do Expo Router pois tive bastante dificuldade com as Nested Routes, então na minha visão o melhor seria criar só um componente que apareça e suma da tela, colocando uma animação talvez.

Se tiver algo em mente, coloca aqui pra gente trocar uma ideia sobre isso. 💜

**Comment by LuizHAP** [comment]
@RennanD Acredito que seja exatamente esse menu. Estou com alguns problemas para instalar o phosphor react native no projeto. Manda o seu discord dps que eu te chamo pra conversarmos, o que acha?

**Comment by rodrigorgtic** [comment]
@RennanD e @LuizHAP é possível fazer a integração do Drawer com o Expo Router. Poss ajudar com isso.
Estou subindo uma PR com essa estrutura já configurada pra vocês seguirem. Pode ser? 💜

**Comment by sdavi38** [comment]
Boa noite tenho trabalhado nesta task

**Comment by sdavi38** [comment]
posso mandar como ficou o meu código

**Comment by LuizHAP** [comment]
@sdavi38 criei a PR #79 se quiser dar uma olhada para ver como ficou!
