### ISSUE TITLE
Pasta padrão do App mobile

### ISSUE THREAD

**Issue by RennanD** [diego3g/rsxp-2023#83]
Acho melhor definirmos a utilização da pasta `app` como padrão para desenvolvimento da parte mobile. Como o Expo Router está funcionando lá e alguns componentes já foram criados lá, na minha opinião vale mais centralizar todos os outros recursos lá. 💜

**Comment by diego3g** [comment]
Podemos colocar tudo dentro da pasta app mesmo que não sejam rotas? Não manjo muito do Expo Router, mas no Next.js a gente evita colocar tudo na pasta app, deixamos lá somente pra arquivos relacionados às rotas da aplicação.

**Comment by nitoba** [comment]
@RennanD infelizmente isso não é possível, qualquer arquivo dentro da pasta app se torna automaticamente uma rota.
![IMG_20230406_184040](https://user-images.githubusercontent.com/38570443/230499203-b724d040-ebcf-4357-b9b4-adec43234395.jpg)

**Comment by melquisedeque-magalhaes** [comment]
ai fica a duvida atualmente na pasta app, nos temos uma pasta de componentes, @types, assets, fora as outras pastas que são realmente rotas da aplicação, essas outras pastas acho melhor ficar dentro da pasta src e deixar dentro de app, realmente so as rotas da aplicação, o mais interessante seria se pudéssemos colocar a pasta app dentro da pasta src mas não sei se e possível hoje com o expo router.

**Comment by rodrigorgtic** [comment]
@melquisedeque-magalhaes, me parece ser possível definir a variável de ambiente no arquivo babel.config.js apontando o App dentro da pasta src com process.env.EXPO_ROUTER_APP_ROOT = __dirname + "/src/app";

**Comment by melquisedeque-magalhaes** [comment]
> @melquisedeque-magalhaes e @RennanD me parece ser possível definir a variável de ambiente no arquivo babel.config.js apontando o App dentro da pasta src com ```process.env.EXPO_ROUTER_APP_ROOT = __dirname + "/src/app";```
> 
> Que tal essa tentativa?
> 
> 

Vou testar aqui para ver se vai kkk

**Comment by melquisedeque-magalhaes** [comment]
@rodrigorgtic mano deu ruim, não funcionou

![Capturar_select-area_20230406225739](https://user-images.githubusercontent.com/43079783/230525297-e7b34d61-75bf-4d3a-a4f6-054cb4c67eee.png)

![Capturar_select-area_20230406225754](https://user-images.githubusercontent.com/43079783/230525307-390438ca-2c56-4e00-b004-fe4d191d392f.png)

**Comment by nitoba** [comment]
@melquisedeque-magalhaes tenta usar o 'require' ao invés do 'import' pra quando for arquivos js

**Comment by melquisedeque-magalhaes** [comment]
> @melquisedeque-magalhaes tenta usar o 'require' ao invés do 'import' pra quando for arquivos js

usei mesmo assim não foi mano.

![Capturar_select-area_20230406233625](https://user-images.githubusercontent.com/43079783/230529801-455aaa85-74b0-4c4a-887b-d34fa60f4bf6.png)

**Comment by nitoba** [comment]
Estranho, pois esse erro da quando vc executa o app fora da pasta mobile

**Comment by melquisedeque-magalhaes** [comment]
> Estranho, pois esse erro da quando vc executa o app fora da pasta mobile

erra isso mesmo mano, mas mesmo assim ele não pegou mano, ele não conseguiu pegar a pasta app dentro da pasta src

![Capturar_select-area_20230406234243](https://user-images.githubusercontent.com/43079783/230530520-bf9242bc-9c0c-4222-a10f-6a771f9a9072.png)

**Comment by rodrigorgtic** [comment]
Galera, vou olhar aqui e já retorno pra vocês com a solução. 💜

**Comment by vinifraga** [comment]
Acho que podemos fechar essa issue @diego3g
