### ISSUE TITLE
 [0017] Buscar ingresso vinculado

### ISSUE THREAD

**Issue by trolliama** [diego3g/rsxp-2023#86]
Eu sei que ainda falta o esquema da comunicação que será feita entre o aplicativo e o backend mas tomei a liberdade de ir testando algumas coisas. Gostaria de trabalhar nesta feature quando o esquema do contrato estiver completo :smile:

Fiz um esquema de como mais ou menos eu imagino que seria feito essa feature:

// app.controller.ts
```typescript
import { Controller, Get, Param } from '@nestjs/common'
import { PrismaService } from './database/prisma.service'
import { GetTicketDto } from './agreements/retrieveTicket'

@Controller()
export class AppController {
  constructor(private prisma: PrismaService) {}

  ...

  @Get('/users/:userId/tickets/:ticketNumber')
  async getTicket(@Param() params: GetTicketDto) {
    const { userId, ticketNumber } = params

    const ticketUser = await this.prisma.ticketToUser.findUnique({
      where: {
        ticketNumber,
      },
    })

    if (!ticketUser) {
      // TODO: throw error (404 status code?)
      return { data: null }
    }

    if (ticketUser.userId !== userId) {
      // TODO: throw error (403 or 401 status code?)
      return { data: { message: 'unauthorized' } }
    }

    return { data: ticketUser }
  }
}
```

// agreements/retrieveTickets.ts
```typescript
import * as z from 'zod'

export const getTicketDto = z.object({
  userId: z.string(),
  ticketNumber: z.string(),
})

export type GetTicketDto = z.infer<typeof getTicketDto>
```
//schema.prisma

```prisma
model TicketToUser {
  user         User     @relation(fields: [userId], references: [id])
  userId       String   @unique
  ticketNumber String   @unique
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt

  @@id([userId, ticketNumber])
}
```

**Comment by eletroswing** [comment]
O que você acha de removermos a responsabilidade de pesquisa ao banco do controller e passarmos para um service, assim poderemos reultilizar em outras partes do código, caso necessário, bem como criar um controller só para os tickets. 
O Ticket tem mais argumentos, retornados do sympla, como o nome do usuário, email, o texto do código qr, temos que conferir o que vale a pena ser salvo no banco. E uma das coisas que mais me preocupam, é que se um usuário malicioso chegar até essa rota, ele pode registrar todos os ingressos com seu user id, por não termos muitos filtros por agora, como autenticação, segue a [discussão 84](https://github.com/diego3g/rsxp-2023/discussions/84) onde o ponto é levantado!

**Comment by diego3g** [comment]
@trolliama Podemos usar um findUnique direto pelo userId já que cada usuário só terá um ingresso no máximo evitando a necessidade do front-end enviar o número do ingresso.

**Comment by trolliama** [comment]
@diego3g Nesse caso o back apenas retornaria o número do ingresso do usuário correto? Imagino que, após isso,  a partir dele será criado o qr code e este será validado a partir da api do sympla?

**Comment by eletroswing** [comment]
@diego3g  @trolliama  essa questão da segurança, posso tentar fazer um auth guard  integrado ao clark (referenciado na live de [Setup](https://www.youtube.com/watch?v=-QDNtACVIG0&ab_channel=Rocketseat)) e já fazer um pull para deixar essa feature dos tickets mais segura. O que acham?

**Comment by trolliama** [comment]
@eletroswing Acho uma ótima ideia e vi que o pull request foi aceito. Quanto a questão de apenas mandar o id do usuario para pegar e deletar o ticket, a ideia é exatamente essa eu que acabei não entendendo corretamente mas já irei ajeitar

**Comment by trolliama** [comment]
@diego3g  e @eletroswing  Fiz as mudanças usando o auth guard. Por favor deem uma checada e assim que for possível eu faço os testes necessários e abro uma PR.

// app.controller.ts
```typescript
import { Controller, Get, Param, Req, UseGuards } from '@nestjs/common'
import { PrismaService } from './database/prisma.service'
import { ClerkAuthGuard } from './clerk/clerk.guard'
import { RequestWithUser } from './clerk/requestInterface.dto'
import { GetTicketDto } from './agreements/retrieveTicket'

@Controller()
export class AppController {
  constructor(private prisma: PrismaService) {}

  @Get()
  async getUsers() {
    const users = await this.prisma.user.findMany()

    return {
      data: users,
    }
  }

  @Get('/users/:userId/ticket')
  @UseGuards(ClerkAuthGuard)
  async getTicket(@Req() req: RequestWithUser, @Param() params: GetTicketDto) {
    const { userId } = params

    if (req.user.id !== userId) {
      // TODO: throw error (403 or 401 status code?)
      return { data: { message: 'unauthorized' } }
    }

    const ticketUser = await this.prisma.ticketToUser.findUnique({
      where: {
        userId,
      },
    })

    if (!ticketUser) {
      // TODO: throw error (404 status code?)
      return { data: null }
    }

    return { data: ticketUser }
  }
}
```

// agreements/retrieveTickets.ts
```typescript
import * as z from 'zod'

export const getTicketDto = z.object({
  userId: z.string(),
})

export type GetTicketDto = z.infer<typeof getTicketDto>
```

**Comment by eletroswing** [comment]
@trolliama me adiciona no discord pra gente codar isso junto, ai já fazemos o crud de pegar, vincular e deletar o ticekt, ai temos uma evolução juntos, o que acha? tag: Fountai#9077

**Comment by trolliama** [comment]
Massa! Já enviei o pedido

**Comment by trolliama** [comment]
Dei uma atualizada junto com o  @eletroswing  no controller da rota!

Para resolver a issue mais facilmente, foi pensado o modelo completo de crud (presente no seguinte [fork.](https://github.com/trolliama/rsxp-2023)). O código final ficou assim(isolando a parte de buscar o ingresso): 

//schema.prisma
 ```typescript
model Tickets {
  userId       String @unique
  ticketNumber String @unique
  @@id([userId, ticketNumber])
}
```

//src/tickets/tickets.service
```typescript
import { Injectable } from '@nestjs/common'
import { PrismaService } from 'src/database/prisma.service'

@Injectable()
export class TicketsService {
  constructor(private prisma: PrismaService) {}

  async getTicketByUserId(userId: string) {
    return await this.prisma.tickets.findUnique({ where: { userId } })
  }
}
```

//app.controller
```typescript
  @Get('/users/ticket')
  @UseGuards(ClerkAuthGuard)
  async getTicketByUserId(@Req() req: RequestWithUser, @Res() res: Response) {
    const userId = req.user.sessions[0].userId
    const ticketInDb = await this.ticketsService.getTicketByUserId(userId)

    if (!ticketInDb) {
      return res
        .status(404)
        .json({ data: null, error: 'Ticket não encontrado' })
    }

    if (ticketInDb.userId !== userId) {
      res
        .status(403)
        .json({ data: null, error: 'O conteúdo pertence a outro usuário.' })
    }
    return {
      data: ticketInDb,
    }
  }
```

**Comment by diego3g** [comment]
Fala @trolliama, implementei essa parte de link nos últimos commits que fiz e ficou bem legal caso queira dar uma olhada! Obrigado! <3

Agora na v2 vai ter muito mais coisa pra implementar!
